Feat/escape hyphen
Monad-Inc/target-postgres pull request #1
Opened 2022-08-10 21:09 UTC by echen805

## Problem

Replace the hyphens with underscores so a flow can succeed

## Proposed changes

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. 
If it fixes a bug or resolves a feature request, be sure to link to that issue._

## Types of changes

What types of changes does your code introduce to PipelineWise?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] Description above provides context of the change
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Unit tests for changes (not needed for documentation changes)
- [ ] CI checks pass with my changes
- [ ] Bumping version in `setup.py` is an individual PR and not mixed with feature or bugfix PRs
- [ ] Commit message/PR title starts with `[AP-NNNN]` (if applicable. AP-NNNN = JIRA ID)
- [ ] Branch name starts with `AP-NNN` (if applicable. AP-NNN = JIRA ID)
- [ ] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [ ] Relevant documentation is updated including usage instructions

2022-08-10 21:30 UTC, Jo-Con-El requested changes
It should instead quote the DB name.

2022-08-10 22:12 UTC, Jo-Con-El requested changes

2022-08-10 22:12 UTC, Jo-Con-El commented on target_postgres/db_sync.py
> +        return f'"{self.schema_name}""."{pg_table_name.lower()}"'
You put two double quotes here.

2022-08-11 00:30 UTC, Jo-Con-El requested changes
There are a million other places where this is going to be a problem, I think:
Line 457:
```
query = "GRANT USAGE ON SCHEMA {} TO GROUP {}".format(schema_name, grantee)
```
Line 462:
```
query = "GRANT SELECT ON ALL TABLES IN SCHEMA {} TO GROUP {}".format(schema_name, grantee)
```

2022-08-11 00:30 UTC, Jo-Con-El commented on target_postgres/db_sync.py
> +            'SELECT table_name FROM information_schema.tables WHERE table_schema = "%s"',
I don't think double-quotes will do the trick:
```
monad=# SELECT table_name FROM information_schema.tables WHERE table_schema = acme-inc;
ERROR:  column "acme" does not exist
LINE 1: ...ROM information_schema.tables WHERE table_schema = acme-inc;
                                                              ^
monad=# SELECT table_name FROM information_schema.tables WHERE table_schema = "acme-inc";
ERROR:  column "acme-inc" does not exist
LINE 1: ...OM information_schema.tables WHERE table_schema = "acme-inc"...
                                                             ^
monad=# SELECT table_name FROM information_schema.tables WHERE table_schema = 'acme-inc';
 table_name 
------------
(0 rows)
```

2022-08-11 00:30 UTC, Jo-Con-El commented on target_postgres/db_sync.py
> +        return f'"{self.schema_name}"."{pg_table_name.lower()}"'
I'm fairly sure that this won't work.  Double quotes are used for identifiers, but single quotes are used for strings (which is what you want here).

2022-08-22 20:21 UTC, cnuss approved these changes

2022-08-22 20:42 UTC, merged